package ro.sparktech24345.logicore.core;

public enum Button {
    CROSS1, CIRCLE1, SQUARE1, TRIANGLE1,
    DPAD_UP1, DPAD_DOWN1, DPAD_RIGHT1, DPAD_LEFT1,
    LEFT_STICK_X1, LEFT_STICK_Y1,
    RIGHT_STICK_X1, RIGHT_STICK_Y1,
    LEFT_TRIGGER1, RIGHT_TRIGGER1,
    LEFT_BUMPER1, RIGHT_BUMPER1,
    LEFT_STICK_BUTTON1, RIGHT_STICK_BUTTON1,
    OPTIONS1, SHARE1,

    CROSS2, CIRCLE2, SQUARE2, TRIANGLE2,
    DPAD_UP2, DPAD_DOWN2, DPAD_RIGHT2, DPAD_LEFT2,
    LEFT_STICK_X2, LEFT_STICK_Y2,
    RIGHT_STICK_X2, RIGHT_STICK_Y2,
    LEFT_TRIGGER2, RIGHT_TRIGGER2,
    LEFT_BUMPER2, RIGHT_BUMPER2,
    LEFT_STICK_BUTTON2, RIGHT_STICK_BUTTON2,
    OPTIONS2, SHARE2,

    NONE
}
