plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    namespace 'ro.sparktech24345.logicore'
    //noinspection GradleDependency
    compileSdk 34

    defaultConfig {
        minSdk 24
        //noinspection ExpiredTargetSdkVersion
        targetSdk 28
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    // Removed resolutionStrategy to avoid polluting the root project

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    //noinspection Aligned16KB
    compileOnly 'org.firstinspires.ftc:RobotCore:12.0.0'
    compileOnly 'org.firstinspires.ftc:Hardware:12.0.0'
    compileOnly 'org.firstinspires.ftc:FtcCommon:12.0.0'
    compileOnly 'org.firstinspires.ftc:Vision:12.0.0'

    implementation 'dev.frozenmilk.dairy:CachingHardware:1.0.0'
    implementation 'org.solverslib:photon:0.3.5'

    // Blaze FTC
    implementation "dev.anygeneric:blazeftc:0.1.61"
    implementation 'dev.anygeneric:blazeftc_pedro:0.1.61'
}


afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = 'com.github.andrei-147'
                artifactId = 'LogiCore'
                version = project.version 
            }
        }
    }
}
